### ISSUE TITLE
Allow for relative path in addition to URI

### ISSUE THREAD

**Issue by slightlytyler** [maroshii/sdktor#4]
First argument to `sdktor` is a URI but in DTR's case we operate on the same origin and need to make requests using relative paths. Funny enough it works if I do `sdktor('http:')`

**Comment by maroshii** [comment]
This seems to work:

```js
sdktor('/version')
  .get('')()
  .then(console.log)
  .catch(console.error);
```

Either way, a test needs to be added for this since all the tests are using a single sdktor instance with an absolute domain name.
